
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import PrivateRegisterContractArtifactJson from '../src/contracts/target/private_register-PrivateRegister.json' assert { type: 'json' };
export const PrivateRegisterContractArtifact = loadContractArtifact(PrivateRegisterContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PrivateRegister;
 */
export class PrivateRegisterContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, PrivateRegisterContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, PrivateRegisterContract.artifact, wallet) as Promise<PrivateRegisterContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<PrivateRegisterContract>(PublicKeys.default(), wallet, PrivateRegisterContractArtifact, PrivateRegisterContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<PrivateRegisterContract>(publicKeys, wallet, PrivateRegisterContractArtifact, PrivateRegisterContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PrivateRegisterContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PrivateRegisterContract['methods'][M]>
  ) {
    return new DeployMethod<PrivateRegisterContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PrivateRegisterContractArtifact,
      PrivateRegisterContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PrivateRegisterContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PrivateRegisterContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'root' | 'credentials'> {
      return {
        root: {
      slot: new Fr(1n),
    },
credentials: {
      slot: new Fr(2n),
    }
      } as ContractStorageLayout<'root' | 'credentials'>;
    }
    

  public static get notes(): ContractNotes<'CredentialNotes'> {
    return {
      CredentialNotes: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'CredentialNotes'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_credential_note(flag: integer, claim: field) */
    add_credential_note: ((flag: (bigint | number), claim: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init_credential_note(flag: integer) */
    init_credential_note: ((flag: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** read_all_credentials(addr: struct) */
    read_all_credentials: ((addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** read_credential(claim_type: integer, addr: struct) */
    read_credential: ((claim_type: (bigint | number), addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** read_credential_hash(claim_type: integer, addr: struct) */
    read_credential_hash: ((claim_type: (bigint | number), addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** read_root(addr: struct) */
    read_root: ((addr: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_verification_root(new_root: field) */
    update_verification_root: ((new_root: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_note_in_merkle_tree(claim_type: integer, siblings: array, indices: array, expected_root: field) */
    verify_note_in_merkle_tree: ((claim_type: (bigint | number), siblings: FieldLike[], indices: (bigint | number)[], expected_root: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
