
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import ZkPokeContractArtifactJson from '../src/zkpoke/target/zkpoke-ZkPoke.json' assert { type: 'json' };
export const ZkPokeContractArtifact = loadContractArtifact(ZkPokeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ZkPoke;
 */
export class ZkPokeContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, ZkPokeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, ZkPokeContract.artifact, wallet) as Promise<ZkPokeContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<ZkPokeContract>(PublicKeys.default(), wallet, ZkPokeContractArtifact, ZkPokeContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<ZkPokeContract>(publicKeys, wallet, ZkPokeContractArtifact, ZkPokeContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ZkPokeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<ZkPokeContract['methods'][M]>
  ) {
    return new DeployMethod<ZkPokeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      ZkPokeContractArtifact,
      ZkPokeContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ZkPokeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(ZkPokeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'regs' | 'public_regs' | 'userinfo' | 'intention' | 'pokes' | 'nullifier_storage'> {
      return {
        regs: {
      slot: new Fr(1n),
    },
public_regs: {
      slot: new Fr(2n),
    },
userinfo: {
      slot: new Fr(3n),
    },
intention: {
      slot: new Fr(4n),
    },
pokes: {
      slot: new Fr(5n),
    },
nullifier_storage: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'regs' | 'public_regs' | 'userinfo' | 'intention' | 'pokes' | 'nullifier_storage'>;
    }
    

  public static get notes(): ContractNotes<'PokeNote' | 'UserInfo' | 'AddressCommit'> {
    return {
      PokeNote: {
          id: new NoteSelector(0),
        },
UserInfo: {
          id: new NoteSelector(1),
        },
AddressCommit: {
          id: new NoteSelector(2),
        }
    } as ContractNotes<'PokeNote' | 'UserInfo' | 'AddressCommit'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_commitment(commit_hash: field) */
    create_commitment: ((commit_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_address(instagram_hash: field) */
    get_address: ((instagram_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_intention(commit_hash: field) */
    get_intention: ((commit_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pokes(owner: struct, page: integer) */
    get_pokes: ((owner: AztecAddressLike, page: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** nullify(nullifier: field) */
    nullify: ((nullifier: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** poke(instagram_id_receiver: string, receiver_addr: struct, randomness: field, mask: integer) */
    poke: ((instagram_id_receiver: string, receiver_addr: AztecAddressLike, randomness: FieldLike, mask: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register(instagram_id: string) */
    register: ((instagram_id: string) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_info(instagram_id: string, full_name: string, partial_name: string, nationality: string) */
    register_info: ((instagram_id: string, full_name: string, partial_name: string, nationality: string) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** respond_poke(commit_hash: field, intention: integer, sender: struct) */
    respond_poke: ((commit_hash: FieldLike, intention: (bigint | number), sender: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** trial(caller: struct, sender: struct) */
    trial: ((caller: AztecAddressLike, sender: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_commitment(commit_hash: field, intention: integer) */
    update_commitment: ((commit_hash: FieldLike, intention: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
